version: '3.6'
services:
  backend-app:
    build:
      context: .
      target: service
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8080
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf  # MySQLの日本語文字化け対策
    ports:
      - 33306:3306
    env_file:
      - .env
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .env
    volumes:
      - minio_data:/export
    command: server /export --console-address ":9001"
volumes:
  mysql_data:
  minio_data:
