openapi: 3.0.3
info:
  title: 家具マッチングサービス
  description: 画像によるレコメンド機能を添えて
  version: 1.0.0
servers:
  - url: http://localhost:8000
tags:
  - name: OK
    description: Check API status
  - name: User
    description: ユーザーアカウント管理
  - name: Furniture
    description: 家具管理
  - name: Trade
    description: 取引機能
  - name: Recommendation
    description: レコメンド機能

paths:
  /ok:
    get:
      tags:
        - OK
      summary: Check API status
      responses:
        '200':
          description: API is running
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OKResponse'
  /sign_up:
    post:
      tags:
        - User
      summary: sign up
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
      responses:
        '200':
          description: User registered successfully
        '400':
          description: バリデーションエラー
  /login:
    post:
      tags:
        - User
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: バリデーションエラー
  /logout:
    post:
      tags:
        - User
      summary: User logout
      responses:
        '200':
          description: User logged out successfully
  /furniture:
    post:
      tags:
        - Furniture
      summary: Register new furniture
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterFurnitureRequest'
      responses:
        '200':
          description: Furniture registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FurnitureResponse'
    get:
      tags:
        - Furniture
      summary: Get list of furniture
      parameters:
        - name: user_id
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Furniture list retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FurnitureListResponse'
  /furniture/{furniture_id}:
    get:
      tags:
        - Furniture
      summary: Get furniture details
      parameters:
        - name: furniture_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Furniture details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FurnitureResponse'
        '400':
          description: バリデーションエラー
    delete:
      tags:
        - Furniture
      summary: Delete furniture
      parameters:
        - name: furniture_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Furniture deleted successfully
        '400':
          description: バリデーションエラー
  /trades:
    post:
      tags:
        - Trade
      summary: Request a trade
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestTradeRequest'
      responses:
        '200':
          description: Trade requested successfully
        '400':
          description: バリデーションエラー
    get:
      tags:
        - Trade
      summary: Get list of trades history
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Trade list retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradeListResponse'
  /trades/{trade_id}:
    put:
      tags:
        - Trade
      summary: Update trade status
      parameters:
        - name: trade_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTradeRequest'
      responses:
        '200':
          description: Trade status updated successfully
        '400':
          description: バリデーションエラー
  /trades/{trade_id}/isChecked:
    put:
      tags:
        - Trade
      summary: Update isChecked status
      parameters:
        - name: trade_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateIsCheckedRequest'
      responses:
        '200':
          description: Trade status updated successfully
        '400':
          description: バリデーションエラー
  /recommend:
    post:
      tags:
        - Recommendation
      summary: Get furniture recommendations based on room photo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecommendRequest'
      responses:
        '200':
          description: Furniture recommendations retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecommendResponse'

components:
  schemas:
    OKResponse:
      type: object
      properties:
        msg:
          type: string
    SignUpRequest:
      type: object
      required:
        - username
        - password
        - address
      properties:
        username:
          type: string
        password:
          type: string
        address:
          type: string
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        userId:
          type: integer
    RegisterFurnitureRequest:
      type: object
      required:
        - userId
        - product_name
        - image
        - description
        - height
        - width
        - depth
        - category
        - color
        - start_date
        - end_date
        - trade_place
        - condition
      properties:
        userId:
          type: integer
        product_name:
          type: string
        image:
          type: string
          format: binary
        description:
          type: string
        height:
          type: number
        width:
          type: number
        depth:
          type: number
        category:
          type: string
        color:
          type: string
        start_date:
          type: string
          format: date
        end_date: 
          type: string
          format: date
        trade_place:
          type: string
        condition:
          type: integer
    FurnitureListResponse:
      type: object
      properties:
        furniture:
          type: array
          items:
            $ref: '#/components/schemas/FurnitureResponse'
    FurnitureResponse:
      type: object
      properties:
        furniture_id:
          type: integer
        product_name:
          type: string
        image:
          type: string
          format: binary
        description:
          type: string
        size:
          type: string
        category:
          type: string
        color:
          type: string
        username:
          type: string
        tradeStatus:
          type: integer
    RequestTradeRequest:
      type: object
      required:
        - furnitureId
        - userId
        - trade_date
      properties:
        furnitureId:
          type: integer
        userId:
          type: integer
        trade_date:
          type: string
          format: date
    TradeResponse:
      type: object
      properties:
        tradeId:
          type: integer
        image:
          type: string
          format: binary
        furnitureId:
          type: integer
        giverId:
          type: integer
        receiverId:
          type: integer
        is_checked:
          type: boolean
    TradeListResponse:
      type: object
      properties:
        trades:
          type: array
          items:
            $ref: '#/components/schemas/TradeResponse'
    UpdateTradeRequest:
      type: object
      required:
        - status
      properties:
        status:
          type: integer
    UpdateIsCheckedRequest:
      type: object
      required:
        - is_checked
      properties:
        is_checked:
          type: boolean
    RecommendRequest:
      type: object
      required:
        - roomPhoto
      properties:
        roomPhoto:
          type: string
    RecommendResponse:
      type: object
      properties:
        recommendations:
          type: array
          items:
            type: object
            properties:
              furnitureId:
                type: integer
              image:
                type: string
                format: binary
              description:
                type: string
              size:
                type: string
              category:
                type: string
