# coding: utf-8

"""
    家具マッチングサービス

    画像によるレコメンド機能を添えて

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBytes, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class FurnitureResponse(BaseModel):
    """
    FurnitureResponse
    """ # noqa: E501
    furniture_id: Optional[StrictInt] = None
    product_name: Optional[StrictStr] = None
    image: Optional[Union[StrictBytes, StrictStr]] = None
    description: Optional[StrictStr] = None
    size: Optional[StrictStr] = None
    category: Optional[StrictStr] = None
    color: Optional[StrictStr] = None
    username: Optional[StrictStr] = None
    trade_status: Optional[StrictInt] = Field(default=None, alias="tradeStatus")
    __properties: ClassVar[List[str]] = ["furniture_id", "product_name", "image", "description", "size", "category", "color", "username", "tradeStatus"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FurnitureResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of FurnitureResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "furniture_id": obj.get("furniture_id"),
            "product_name": obj.get("product_name"),
            "image": obj.get("image"),
            "description": obj.get("description"),
            "size": obj.get("size"),
            "category": obj.get("category"),
            "color": obj.get("color"),
            "username": obj.get("username"),
            "tradeStatus": obj.get("tradeStatus")
        })
        return _obj


